blogs/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from blogs.views import BlogListView,BlogDetailView, BlogCommentView
app_name = 'blogs'





urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('comment/<int:pk>/', BlogCommentView.as_view(), name='comment'),

]

conf/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
            path('admin/', admin.site.urls),
            path('', include('pages.urls', namespace="pages")),
            path('blogs/', include('blogs.urls', namespace="blogs")),
            path('products/', include('products.urls', namespace="products")),
            path('users/', include('users.urls', namespace="users")),
            path('orders/', include('orders.urls', namespace="orders"))

)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, order_create, order_history_view

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/', order_create, name='order'),
    path('history/', order_history_view, name='history'),
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from pages.views import HomePageView, ContactTemplateView, ThankYouView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
    path('contact/thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

]

users/urls.py
from django.urls import path
from users.views import LoginView, RegisterView, verify_email, logout_view, About, AccountView, CartView, WishlistView, \
    Faq

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/email',verify_email, name='code'),
    path('logout/', logout_view ,name='logout'),
    path('about/', About.as_view(), name='about'),
    path('accounts/', AccountView.as_view(), name='accounts'),
    path('cart/', CartView.as_view(), name='cart'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('faq/', Faq.as_view(), name='faq'),

]

templates/layouts/footer.html
{% load static %} {% load i18n %}
<div class="footer">
  <!-- Begin Footer Static Top Area -->
  <div class="footer-static-top">
    <div class="container">
      <!-- Begin Footer Shipping Area -->
      <div class="footer-shipping pt-60 pb-55 pb-xs-25">
        <div class="row">
          <!-- Begin Li's Shipping Inner Box Area -->
          <div class="col-lg-3 col-md-6 col-sm-6 pb-sm-55 pb-xs-55">
            <div class="li-shipping-inner-box">
              <div class="shipping-icon">
                <img
                  src="{%static 'images/shipping-icon/1.png '%}"
                  alt="Shipping Icon"
                />
              </div>
              <div class="shipping-text">
                <h2>{% trans 'Free Delivery' %}</h2>
                <p>
                  {% trans 'And free returns. See checkout for delivery dates.'
                  %}
                </p>
              </div>
            </div>
          </div>
          <!-- Li's Shipping Inner Box Area End Here -->
          <!-- Begin Li's Shipping Inner Box Area -->
          <div class="col-lg-3 col-md-6 col-sm-6 pb-sm-55 pb-xs-55">
            <div class="li-shipping-inner-box">
              <div class="shipping-icon">
                <img
                  src="{%static 'images/shipping-icon/2.png '%}"
                  alt="Shipping Icon"
                />
              </div>
              <div class="shipping-text">
                <h2>{% trans 'Safe Payment' %}</h2>
                <p>
                  {% trans 'Pay with the world most popular and secure payment
                  methods.' %}
                </p>
              </div>
            </div>
          </div>
          <!-- Li's Shipping Inner Box Area End Here -->
          <!-- Begin Li's Shipping Inner Box Area -->
          <div class="col-lg-3 col-md-6 col-sm-6 pb-xs-30">
            <div class="li-shipping-inner-box">
              <div class="shipping-icon">
                <img
                  src="{%static 'images/shipping-icon/3.png '%}"
                  alt="Shipping Icon"
                />
              </div>
              <div class="shipping-text">
                <h2>{% trans 'Shop with Confidence' %}</h2>
                <p>
                  {% trans 'Our Buyer Protection covers your purchasefrom click
                  to delivery.' %}
                </p>
              </div>
            </div>
          </div>
          <!-- Li's Shipping Inner Box Area End Here -->
          <!-- Begin Li's Shipping Inner Box Area -->
          <div class="col-lg-3 col-md-6 col-sm-6 pb-xs-30">
            <div class="li-shipping-inner-box">
              <div class="shipping-icon">
                <img
                  src="{%static 'images/shipping-icon/4.png '%}"
                  alt="Shipping Icon"
                />
              </div>
              <div class="shipping-text">
                <h2>24/7 {% trans 'Help Center' %}</h2>
                <p>
                  {% trans 'Have a question? Call a Specialist or chat online.'
                  %}
                </p>
              </div>
            </div>
          </div>
          <!-- Li's Shipping Inner Box Area End Here -->
        </div>
      </div>
      <!-- Footer Shipping Area End Here -->
    </div>
  </div>
  <!-- Footer Static Top Area End Here -->
  <!-- Begin Footer Static Middle Area -->
  <div class="footer-static-middle">
    <div class="container">
      <div class="footer-logo-wrap pt-50 pb-35">
        <div class="row">
          <!-- Begin Footer Logo Area -->
          <div class="col-lg-4 col-md-6">
            <div class="footer-logo">
              <img
                src="{%static 'images/menu/logo/1.jpg '%}"
                alt="Footer Logo"
              />
              <p class="info">
                {% trans 'We are a team of designers and developers that create
                high quality HTML Template & Woocommerce, Shopify Theme.' %}
              </p>
            </div>
            <ul class="des">
              <li>
                <span>{%trans 'Address' %}: </span>
                {% trans ' 6688Princess Road, London, Greater London BAS 23JK,
                UK' %}
              </li>
              <li>
                <span>{% trans 'Phone' %}: </span>
                <a href="#">(+998) 94 007 41 74</a>
              </li>
              <li>
                <span>Email: </span>
                <a href="ahmedovafazilat300@gmail.com"
                  >ahmedovafazilat300@gmail.com</a
                >
              </li>
            </ul>
          </div>
          <!-- Footer Logo Area End Here -->
          <!-- Begin Footer Block Area -->
          <div class="col-lg-2 col-md-3 col-sm-6">
            <div class="footer-block">
              <h3 class="footer-block-title">{% trans 'Product' %}</h3>
              <ul>
                <li><a href="#">{% trans 'Prices drop' %}</a></li>
                <li><a href="#">{% trans 'New products' %}</a></li>
                <li><a href="#">{% trans 'Best sales' %}</a></li>
                <li><a href="#">{% trans 'Contact us' %}</a></li>
              </ul>
            </div>
          </div>
          <!-- Footer Block Area End Here -->
          <!-- Begin Footer Block Area -->
          <div class="col-lg-2 col-md-3 col-sm-6">
            <div class="footer-block">
              <h3 class="footer-block-title">{% trans 'Our company' %}</h3>
              <ul>
                <li><a href="#">{% trans 'Delivery' %}</a></li>
                <li><a href="#">{% trans 'Legal Notice' %}</a></li>
                <li><a href="#">{% trans 'About us' %}</a></li>
                <li><a href="#">{% trans 'Contact us' %}</a></li>
              </ul>
            </div>
          </div>
          <!-- Footer Block Area End Here -->
          <!-- Begin Footer Block Area -->
          <div class="col-lg-4">
            <div class="footer-block">
              <h3 class="footer-block-title">{% trans 'Follow Us' %}</h3>
              <ul class="social-link">
                <li class="twitter">
                  <a
                    href="https://twitter.com/"
                    data-toggle="tooltip"
                    target="_blank"
                    title="Twitter"
                  >
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
                <li class="rss">
                  <a
                    href="https://rss.com/"
                    data-toggle="tooltip"
                    target="_blank"
                    title="RSS"
                  >
                    <i class="fa fa-rss"></i>
                  </a>
                </li>
                <li class="google-plus">
                  <a
                    href="https://www.plus.google.com/discover"
                    data-toggle="tooltip"
                    target="_blank"
                    title="Google Plus"
                  >
                    <i class="fa fa-google-plus"></i>
                  </a>
                </li>
                <li class="facebook">
                  <a
                    href="https://www.facebook.com/"
                    data-toggle="tooltip"
                    target="_blank"
                    title="Facebook"
                  >
                    <i class="fa fa-facebook"></i>
                  </a>
                </li>
                <li class="youtube">
                  <a
                    href="https://www.youtube.com/"
                    data-toggle="tooltip"
                    target="_blank"
                    title="Youtube"
                  >
                    <i class="fa fa-youtube"></i>
                  </a>
                </li>
                <li class="instagram">
                  <a
                    href="https://www.instagram.com/"
                    data-toggle="tooltip"
                    target="_blank"
                    title="Instagram"
                  >
                    <i class="fa fa-instagram"></i>
                  </a>
                </li>
              </ul>
            </div>
            <!-- Begin Footer Newsletter Area -->
            <div class="footer-newsletter">
              <h4>{% trans 'Sign up to newsletter' %}</h4>
              <form
                action="#"
                method="post"
                id="mc-embedded-subscribe-form"
                name="mc-embedded-subscribe-form"
                class="footer-subscribe-form validate"
                target="_blank"
                novalidate
              >
                <div id="mc_embed_signup_scroll">
                  <div id="mc-form" class="mc-form subscribe-form form-group">
                    <input
                      id="mc-email"
                      type="email"
                      autocomplete="off"
                      placeholder="{% trans 'Enter your email' %}"
                    />
                    <button class="btn" id="mc-submit">
                      {% trans 'Subscribe' %}
                    </button>
                  </div>
                </div>
              </form>
            </div>
            <!-- Footer Newsletter Area End Here -->
          </div>
          <!-- Footer Block Area End Here -->
        </div>
      </div>
    </div>
  </div>
  <!-- Footer Static Middle Area End Here -->
  <!-- Begin Footer Static Bottom Area -->

  <!-- Footer Static Bottom Area End Here -->
</div>
<!-- Footer Area End Here -->
<!-- Begin Quick View | Modal Area -->

templates/layouts/head.html
{% load static %}
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Home Version One || limupa - Digital Products Store eCommerce Bootstrap 4 Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{%static 'images/favicon.png '%}">
        <!-- Material Design Iconic Font-V2.2.0 -->
        <link rel="stylesheet" href="{%static 'css/material-design-iconic-font.min.css '%}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{%static 'css/font-awesome.min.css '%}">
        <!-- Font Awesome Stars-->
        <link rel="stylesheet" href="{%static 'css/fontawesome-stars.css '%}">
        <!-- Meanmenu CSS -->
        <link rel="stylesheet" href="{%static 'css/meanmenu.css '%}">
        <!-- owl carousel CSS -->
        <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css '%}">
        <!-- Slick Carousel CSS -->
        <link rel="stylesheet" href="{%static 'css/slick.css '%}">
        <!-- Animate CSS -->
        <link rel="stylesheet" href="{%static 'css/animate.css '%}">
        <!-- Jquery-ui CSS -->
        <link rel="stylesheet" href="{%static 'css/jquery-ui.min.css '%}">
        <!-- Venobox CSS -->
        <link rel="stylesheet" href="{%static 'css/venobox.css '%}">
        <!-- Nice Select CSS -->
        <link rel="stylesheet" href="{%static 'css/nice-select.css '%}">
        <!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{%static 'css/magnific-popup.css '%}">
        <!-- Bootstrap V4.1.3 Fremwork CSS -->
        <link rel="stylesheet" href="{%static 'css/bootstrap.min.css '%}">
        <!-- Helper CSS -->
        <link rel="stylesheet" href="{%static 'css/helper.css '%}">
        <!-- Main Style CSS -->
        <link rel="stylesheet" href="{%static 'style.css'%}">
        <!-- Responsive CSS -->
        <link rel="stylesheet" href="{%static 'css/responsive.css '%}">
        <!-- Modernizr js -->
        <script src="{%static 'js/vendor/modernizr-2.8.3.min.js '%}"></script>
    </head>

templates/layouts/header-base.html
{% load static %} {% load my_tags %} {% load i18n %}

<header>
  <!-- Begin Header Top Area -->
  <div class="header-top">
    <div class="container">
      <div class="row">
        <!-- Begin Header Top Left Area -->
        <div class="col-lg-3 col-md-4">
          <div class="header-top-left">
            <ul class="phone-wrap">
              <li>
                <span>{% trans 'Telephone Enquiry' %}:</span
                ><a href="#">(+998) 94 007 41 74</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- Header Top Left Area End Here -->
        <!-- Begin Header Top Right Area -->
        <div class="col-lg-9 col-md-8">
          <div class="header-top-right">
            <ul class="ht-menu">
              <!-- Begin Setting Area -->
              <li>
                <div class="ht-setting-trigger">
                  <span>{% trans 'Settings' %}</span>
                </div>
                <div class="setting ht-setting">
                  <ul class="ht-setting-list">
                    <li>
                      <a href="{% url 'users:accounts' %}"
                        >{% trans 'My Accounts' %}</a
                      >
                    </li>
                    {%if request.user.is_authenticated%}
                    <li>
                      <a href="{% url 'users:logout'%}">{% trans 'Logout' %}</a>
                    </li>
                    <li>
                      <a href="{% url 'orders:checkout' %}"
                        >{% trans 'Checkout' %}</a
                      >
                    </li>
                    <li>
                      <a href="{% url 'orders:history' %}"
                        >{% trans 'My order' %}</a
                      >
                    </li>
                    <li>
                      <a href="{% url 'users:faq' %}">{% trans 'Faq' %}</a>
                    </li>
                    {%else%}
                    <li>
                      <a href="{% url 'users:login'%}">{% trans 'Log In' %}</a>
                    </li>
                    {%endif%}
                  </ul>
                </div>
              </li>
              <li>
                <span class="language-selector-wrapper"
                  >{% trans 'Language' %} :</span
                >
                <div class="ht-language-trigger">
                  <span>{% trans 'Choose'%} ?</span>
                </div>
                <div class="language ht-language">
                  {% get_available_languages as all_lang %} {% for lang_code,
                  lang_name in all_lang %} {% if lang_name == 'English' or
                  lang_name == 'Uzbek' %}
                  <ul class="ht-setting-list">
                    <li class="active">
                      <a href="{% get_lang_url request lang_code %}"
                        >{{ lang_code|upper }}</a
                      >
                    </li>
                  </ul>
                  {% endif %} {% endfor %}
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="header-middle pl-sm-0 pr-sm-0 pl-xs-0 pr-xs-0">
    <div class="container">
      <div class="row">
        <!-- Begin Header Logo Area -->
        <div class="col-lg-3">
          <div class="logo pb-sm-30 pb-xs-30">
            <a href="index.html">
              <img src="{%static 'images/menu/logo/1.jpg '%}" alt="" />
            </a>
          </div>
        </div>
        <div class="col-lg-9 pl-0 ml-sm-15 ml-xs-15">
          <!-- Begin Header Middle Searchbox Area -->
          <form action="#" class="hm-searchbox">
            <input
              type="text"
              name="q"
              value="{{ request.GET.q }}"
              placeholder="{% trans 'Enter your search key ...' %}"
            />
            <button class="li-btn" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </form>
          <!-- Header Middle Searchbox Area End Here -->
          <!-- Begin Header Middle Right Area -->
          <div class="header-middle-right">
            <ul class="hm-menu">
              <!-- Begin Header Middle Wishlist Area -->
              <li class="hm-wishlist">
                <a href="{% url 'users:wishlist' %}">
                  <span class="cart-item-count wishlist-item-count"
                    >{{ request|get_wish_total|length }}</span
                  >
                  <i class="fa fa-heart-o"></i>
                </a>
              </li>
              <!-- Header Middle Wishlist Area End Here -->
              <!-- Begin Header Mini Cart Area -->
              <li class="hm-minicart">
                <div class="hm-minicart-trigger">
                  <span class="item-icon"></span>
                  <span class="item-text"
                    >${{ request|get_cart_total }}
                    <span class="cart-item-count"
                      >{{ request|get_user_cart|length }}</span
                    >
                  </span>
                  {% for product in request|get_user_cart %}
                </div>
                <span></span>
                <div class="minicart">
                  <ul class="minicart-product-list">
                    <li>
                      <a
                        href="single-product.html"
                        class="minicart-product-image"
                      >
                        <img
                          src="{{ product.image.url }}"
                          alt="cart products"
                        />
                      </a>
                      <div class="minicart-product-details">
                        <h6>
                          <a href="single-product.html">{{ product.title }}</a>
                        </h6>
                        <span
                          >{% if product.is_discount %}
                          <span style="color: #14ef31" class="price"
                            >${{ product.get_price }} -
                          </span>
                          <strike style="color: red"
                            >{{ product.price }}</strike
                          >
                          {% else %}
                          <span class="price" style="color: #b714ef"
                            >{% trans 'No discount' %} - ${{ product.price
                            }}</span
                          >
                          {% endif %} x {{ product.count }}</span
                        >
                      </div>
                      <td class="action">
                        <a
                          class="remove"
                          href="{% url 'products:add_or_remove' pk=product.id %}"
                        >
                          <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                      </td>
                    </li>
                    <a href="{% url 'users:cart' %}"
                      >{% trans 'More product' %} ?</a
                    >
                  </ul>
                  <p class="minicart-total">
                    {% trans 'TOTAL' %}:
                    <span>$ {{ request|get_cart_total }}</span>
                  </p>
                  <div class="minicart-button">
                    <a
                      href="{% url 'users:cart' %}"
                      class="li-button li-button-fullwidth li-button-dark"
                    >
                      <span>{% trans 'View Full Cart' %}</span>
                    </a>
                    <a
                      href="{% url 'orders:checkout' %}"
                      class="li-button li-button-fullwidth"
                    >
                      <span>{% trans 'Checkout' %}</span>
                    </a>
                  </div>
                </div>
                {% endfor %}
              </li>
              <!-- Header Mini Cart Area End Here -->
            </ul>
          </div>
          <!-- Header Middle Right Area End Here -->
        </div>
        <!-- Header Middle Right Area End Here -->
      </div>
    </div>
  </div>
  <div class="header-bottom header-sticky d-none d-lg-block d-xl-block">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- Begin Header Bottom Menu Area -->
          <div class="hb-menu">
            <nav>
              <ul>
                <li class="dropdown-holder">
                  <a href="/">{% trans 'Home' %}</a>
                </li>
                <li class="dropdown-holder">
                  <a href="{% url 'blogs:list' %}">{% trans 'Blogs' %}</a>
                </li>
                <li class="dropdown-holder">
                  <a href="{% url 'products:list' %}">{% trans 'Products' %}</a>
                </li>
                <li class="dropdown-holder">
                  <a href="{% url 'pages:contact' %}">{% trans 'Contact' %}</a>
                </li>
                <li class="dropdown-holder">
                  <a href="{% url 'users:about'%}">{% trans 'About' %}</a>
                </li>
              </ul>
            </nav>
          </div>
          <!-- Header Bottom Menu Area End Here -->
        </div>
      </div>
    </div>
  </div>
  <!-- Header Bottom Area End Here -->
  <!-- Begin Mobile Menu Area -->
  <div class="mobile-menu-area d-lg-none d-xl-none col-12">
    <div class="container">
      <div class="row">
        <div class="mobile-menu"></div>
      </div>
    </div>
  </div>
  <!-- Mobile Menu Area End Here -->
</header>

templates/layouts/script.html
{% load static %}
<script src="{%static 'js/vendor/jquery-1.12.4.min.js '%}"></script>
        <!-- Popper js -->
        <script src="{%static 'js/vendor/popper.min.js '%}"></script>
        <!-- Bootstrap V4.1.3 Fremwork js -->
        <script src="{%static 'js/bootstrap.min.js '%}"></script>
        <!-- Ajax Mail js -->
        <script src="{%static 'js/ajax-mail.js '%}"></script>
        <!-- Meanmenu js -->
        <script src="{%static 'js/jquery.meanmenu.min.js '%}"></script>
        <!-- Wow.min js -->
        <script src="{%static 'js/wow.min.js '%}"></script>
        <!-- Slick Carousel js -->
        <script src="{%static 'js/slick.min.js '%}"></script>
        <!-- Owl Carousel-2 js -->
        <script src="{%static 'js/owl.carousel.min.js '%}"></script>
        <!-- Magnific popup js -->
        <script src="{%static 'js/jquery.magnific-popup.min.js '%}"></script>
        <!-- Isotope js -->
        <script src="{%static 'js/isotope.pkgd.min.js '%}"></script>
        <!-- {%static 'Imagesloaded '%} js -->
        <script src="{%static 'js/imagesloaded.pkgd.min.js '%}"></script>
        <!-- Mixitup js -->
        <script src="{%static 'js/jquery.mixitup.min.js '%}"></script>
        <!-- Countdown -->
        <script src="{%static 'js/jquery.countdown.min.js '%}"></script>
        <!-- Counterup -->
        <script src="{%static 'js/jquery.counterup.min.js '%}"></script>
        <!-- Waypoints -->
        <script src="{%static 'js/waypoints.min.js '%}"></script>
        <!-- Barrating -->
        <script src="{%static 'js/jquery.barrating.min.js '%}"></script>
        <!-- Jquery-ui -->
        <script src="{%static 'js/jquery-ui.min.js '%}"></script>
        <!-- Venobox -->
        <script src="{%static 'js/venobox.min.js '%}"></script>
        <!-- Nice Select js -->
        <script src="{%static 'js/jquery.nice-select.min.js '%}"></script>
        <!-- ScrollUp js -->
        <script src="{%static 'js/scrollUp.min.js '%}"></script>
        <!-- Main/Activator js -->
        <script src="{%static 'js/main.js '%}"></script>