conf/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
            path('admin/', admin.site.urls),
            path('', include('pages.urls', namespace="pages")),
            path('blogs/', include('blogs.urls', namespace="blogs")),
            path('products/', include('products.urls', namespace="products")),
            path('users/', include('users.urls', namespace="users")),
            path('orders/', include('orders.urls', namespace="orders"))

)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, order_create, order_history_view

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/', order_create, name='order'),
    path('history/', order_history_view, name='history'),
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from pages.views import HomePageView, ContactTemplateView, ThankYouView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
    path('contact/thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

]

products/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from products.views import ProductListView, ProductDetailView, add_or_remove, add_or_remov

app_name = 'products'





urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('cart/<int:pk>/', add_or_remove, name='add_or_remove'),
    path('wish/<int:pk>/', add_or_remov, name='add_or_remov')

]

products/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.models import TeamModel


class ProductCategoryModel(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

class ProductTagModel(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class ProductColor(models.Model):
    objects = None
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=7)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('color')
        verbose_name_plural = _('colors')


class ProductSizeModel(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('size')
        verbose_name_plural = _('sizes')


class ProductBrand(models.Model):
    objects = None
    name = models.CharField(max_length=100)
    logo = models.ImageField(null=True, blank=True, upload_to='logo')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('manufacture')
        verbose_name_plural = _('manufactures')


class ProductModel(models.Model):
    objects = None
    image = models.ImageField(upload_to='products/')
    image1 = models.ImageField(upload_to='products/')

    title = models.CharField(max_length=100, db_index=True)
    short_info = models.CharField(max_length=200)
    long_description = models.TextField(default="")
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(100), MinValueValidator(0)])
    sku = models.CharField(max_length=10, unique=True)
    count = models.PositiveIntegerField()
    real_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, related_name='products')
    color = models.ManyToManyField(ProductColor, related_name='products')
    tags = models.ManyToManyField(ProductTagModel, related_name='products')
    categories = models.ManyToManyField(ProductCategoryModel, related_name='products')
    sizes = models.ManyToManyField(ProductSizeModel, related_name='sizes')
    author = models.ForeignKey(TeamModel, on_delete=models.CASCADE, related_name='author')


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def is_discount(self):
        return self.discount != 0

    def is_available(self):
        return self.discount != 0

    def get_price(self):
        if self.is_discount():
            return self.price - self.discount * self.price / 100

    def get_related_products(self):
        return ProductModel.objects.filter(categories__in=self.categories.all()).exclude(pk=self.pk).distinct()[:3]

    class Meta:
        ordering = ['title']
        verbose_name = _('product')
        verbose_name_plural = _('products')

products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from products.models import ProductModel, ProductCategoryModel, ProductBrand, ProductColor, ProductTagModel, \
    ProductSizeModel
from users.models import TeamModel


class ProductListView(ListView):
    template_name = 'products/product-list.html'
    model = ProductModel
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        qs = ProductModel.objects.all().order_by('-pk')
        cat = self.request.GET.get('cat')
        tag = self.request.GET.get('tag')
        brand = self.request.GET.get('brand')
        col = self.request.GET.get('col')
        sort = self.request.GET.get('sort')
        q = self.request.GET.get('q')
        sizes = self.request.GET.get('sizes')

        if cat:
            qs = qs.filter(categories__in=cat)
        if tag:
            qs = qs.filter(tags__in=tag)
        if brand:
            qs = qs.filter(brands__in=brand)
        if col:
            qs = qs.filter(color__in=col)
        if sizes:
            qs = qs.filter(sizes__in=sizes)
        if sort:
            if sort == '-price':
                qs = qs.order_by('-real_price')
            else:
                qs = qs.order_by('real_price')
        if sort:
            if sort == 'title':
                qs = qs.order_by('title')
            else:
                qs = qs.order_by('-title')
        if q:
            qs = qs.filter(title__icontains=q)

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        content = super().get_context_data(**kwargs)
        content['categories'] = ProductCategoryModel.objects.all()
        content['brand'] = ProductBrand.objects.all()
        content['color'] = ProductColor.objects.all()
        content['sizes'] = ProductSizeModel.objects.all()
        content['tags'] = ProductTagModel.objects.all()

        return content


class ProductDetailView(DetailView):
    template_name = 'products/product-detail.html'
    model = ProductModel
    context_object_name = 'products'

    def get_object(self, *args, **kwargs):
        return ProductModel.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):
        products = ProductModel.objects.get(id=self.kwargs['pk'])
        content = super().get_context_data(**kwargs)
        content.update({
            'categories': ProductCategoryModel.objects.all(),
            'brand': ProductBrand.objects.all(),
            'color': ProductColor.objects.all(),
            'tags': ProductTagModel.objects.all(),
            'product': ProductModel.objects.all(),
            'author' : TeamModel.objects.all(),
            'sizes' : ProductSizeModel.objects.all()
        })

        return content


def add_or_remove(request, pk):
    cart = request.session.get('cart', [])
    if pk in cart:
        cart.remove(pk)
    else:
        cart.append(pk)
    request.session['cart'] = cart
    return redirect(request.GET.get('next', 'products:list'))

def add_or_remov(request, pk):
    wish = request.session.get('wish', [])
    if pk in wish:
        wish.remove(pk)
    else:
        wish.append(pk)
    request.session['wish'] = wish
    return redirect(request.GET.get('next', 'products:list'))

templates/products/checkout.html
{% load static %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
       <style>

*,
*:before,
*:after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
    background: url('https://wallbox.ru/resize/2560x1600/wallpapers/main2/201732/1502561450598f44aaccc176.46698383.jpg') no-repeat center center fixed;
    background-size: cover;
    padding: 0px;
    min-height: 100vh; /* Background image will cover the entire viewport height */

}

#wrapper-site {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 50vh;
    width: 100%;

}



.cart-grid {
    display: flex;
    flex-direction: column;
    width: 100%;
    align-items: center
}

.check-info {
    background-color: #fff;
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 20px;
     width: 100%;
}

.checkout-personal-step {
    margin-bottom: 20px;
}

.step-title {
    font-size: 1.5em;
    color: #007bff;
    margin-bottom: 10px;
}

.step-title .step-number {
    background-color: #E9D31E;
    color: Black;
    padding: 1px 10px;
    border-radius: 100%;
    margin-right: 50px;
}

.form-group {
    margin-bottom: 16px;
    display: flex;
    justify-content: center;
    width: 100%; /* Kenglikni 100% ga kengaytirish */
}

.form-control {
    width: 100%;
    max-width: 600px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 14px;
    margin:0  40px;
}
}

.btn-primary {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 10px;
    cursor: pointer;
    width: 50%;
    font-size: 10px;
    transition: background-color 0.3s ease;
}

.btn-primary:hover {
    background-color: #0056b3;
}

.pull-xs-right {
    float: right;
    width: 100%;
}

       </style>
    </head>
<!-- checkout31:27-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}

            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Checkout' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!--Checkout Area Strat-->
            <div id="wrapper-site">
                <div class="container">
                    <div class="row">
                        <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                            <div id="main">
                                <div class="cart-grid row">
                                    <div class="col-md-9 check-info">
                                        <div class="checkout-personal-step">
                                            <h3 class="step-title h3 info">
                                                <span class="step-number">1</span>{% trans 'PERSONAL INFORMATION' %}
                                            </h3>
                                        </div>
                                        <div class="content">
                                            <ul class="nav nav-inline">
                                            </ul>
                                            <div class="tab-content">
                                                <div class="tab-pane fade in active show" id="checkout-guest-form" role="tabpanel">
                                                    <form action="{% url 'orders:order' %}" id="customer-form" class="js-customer-form" method="post">
                                                        {% csrf_token %}
                                                        <div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="address" type="text" placeholder="{% trans 'Address' %}">
                                                            </div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="phone" type="text" placeholder="{% trans 'Phone' %}">
                                                            </div>
                                                        </div>
                                                        <div class="clearfix">
                                                            <div class="row">
                                                                <input type="hidden" name="submitCreate" value="1">

                                                                <button class="continue btn btn-primary pull-xs-right" name="continue" data-link-action="register-new-customer" type="submit"
                                                                    value="1">
                                                                    {% trans 'Continue' %}
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Checkout Area End-->
            <!-- Begin Footer Area -->
           {% include 'layouts/footer.html' %}

            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
       {% include 'layouts/script.html' %}

    </body>

<!-- checkout31:27-->
</html>

templates/products/product-detail.html
{% load static %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">

<!-- single-product31:30-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
           {% include 'layouts/header-base.html' %}

            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Product Details' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- content-wraper start -->
            <div class="content-wraper">
                <div class="container">
                    <div class="row single-product-area">
                        <div class="col-lg-5 col-md-6">
                           <!-- Product Details Left -->
                            <div class="product-details-left">
                                        <div class="product-details-images slider-navigation-1">
                                            <div class="lg-image">
                                                <a class="popup-img venobox vbox-item" href="{% url 'products:detail' pk=products.id %}" data-gall="myGallery">
                                                    <img src="{{ products.image.url }}" alt="product image">
                                                </a>
                                            </div>
                                        </div>
                                        <div class="product-details-thumbs slider-thumbs-1">
                                            {% for image in product %}
                                                <div class="sm-image"><img src="{{ image.image.url }}" alt="product image thumb"></div>
                                            {% endfor %}
                                        </div>
                                    </div>
                            <!--// Product Details Left -->
                        </div>
                        <div class="col-lg-7 col-md-6">
                            <div class="product-details-view-content pt-60">
                                <div class="product-info">
                                    <h2>{{ products.title }}</h2>
                                    <span class="product-details-ref">{% trans 'Reference' %}: {{ products.author }}</span>
                                    <div class="price-box pt-20">
                                         {% if products.is_discount %}
                                            <span style="color:#14EF31;" class="price">${{ products.get_price }} - </span>
                                            <strike style="color:red;">{{ products.price }}</strike>
                                        {% else %}
                                            <span class="price" style="color: #B714EF">{% trans 'No discount' %} - ${{ products.price }}</span>
                                        {% endif %}
                                    </div>
                                    <div class="product-desc">
                                        <p>
                                            <span>{{ products.short_info }}
                                            </span>
                                        </p>
                                    </div>
                                    <div class="product-variants">
                                        <div class="produt-variants-size">
                                            <label>{% trans 'Dimension' %}</label>
                                            <select class="nice-select">
                                                {% for size in products.sizes.all %}
                                                <option value="1" title="S" selected="selected">{{ size.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="single-add-to-cart">
                                        <form action="#" class="cart-quantity">
                                            <div class="quantity">
                                                <label>{% trans 'Quantity' %}</label>
                                                <div class="cart-plus-minus">
                                                    <input class="cart-plus-minus-box" value="1" type="text">
                                                </div>
                                            </div>
                                            <button class="add-to-cart" type="submit"><a href="{% url 'products:add_or_remove' pk=products.id %}?next={{request.get_full_path|urlencode}}">{% trans 'add to cart' %}</a></button>
                                        </form>
                                    </div>
                                    <div class="product-additional-info pt-25">
                                        <a class="wishlist-btn" href="{% url 'products:add_or_remov' pk=products.id %}?next={{request.get_full_path|urlencode}}"><i class="fa fa-heart-o"></i>{% trans 'Add to wishlist' %}</a>
                                        <div class="product-social-sharing pt-25">
                                            <ul>
                                                <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i>Facebook</a></li>
                                                <li class="twitter"><a href="https://www.twitter.com/"><i class="fa fa-twitter"></i>Twitter</a></li>
                                                <li class="google-plus"><a href="https://www.google.com/"><i class="fa fa-google-plus"></i>Google +</a></li>
                                                <li class="instagram"><a href="https://www.instagram.com/"><i class="fa fa-instagram"></i>Instagram</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
            <br>
            <br>
            <!-- content-wraper end -->
            <!-- Begin Product Area -->
            <div class="product-area pt-35">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="li-product-tab">
                                <ul class="nav li-product-menu">
                                   <li><a class="active" data-toggle="tab" href="#description"><span>{% trans 'Description' %}</span></a></li>
                                   <li><a data-toggle="tab" href="#product-details"><span>{% trans 'Product Details' %}</span></a></li>
                                </ul>               
                            </div>
                            <!-- Begin Li's Tab Menu Content Area -->
                        </div>
                    </div>
                    <div class="tab-content">
                        <div id="description" class="tab-pane active show" role="tabpanel">
                            <div class="product-description">
                                    <span>{{products.short_info}}</span>
                            </div>
                        </div>
                        <div id="product-details" class="tab-pane" role="tabpanel">
                            <div class="product-details-manufacturer">
                                <a href="#">
                                    <img src="{%static 'images/product-details/admin.png' %}" alt="Product Manufacturer Image">
                                </a>
                                <p><span>{% trans 'Reference' %}</span>- {{ products.author }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Product Area End Here -->
            <!-- Begin Li's Laptop Product Area -->
            <section class="product-area li-laptop-product pt-30 pb-50">
                <div class="container">
                    <div class="row">
                        <!-- Begin Li's Section Area -->
                        <div class="col-lg-12">
                            <div class="li-section-title">
                                <h2>
                                    <span>{{ product.count }} - {% trans 'other products in the same category' %}:</span>
                                </h2>
                            </div>
                            <div class="row">
                                <div class="product-active owl-carousel">
                                    {% for prod in product %}
                                    <div class="col-lg-12">
                                        <!-- single-product-wrap start -->
                                        <div class="single-product-wrap">
                                            <div class="product-image">
                                                <a href="{% url 'products:detail' pk=prod.id %}">
                                                    <img src="{{ prod.image.url }}" alt="Li's Product Image">
                                                </a>
                                                <span class="sticker">{% trans 'New' %}</span>
                                            </div>
                                            <div class="product_desc">
                                                <div class="product_desc_info">
                                                    <div class="product-review">
                                                        <h5 class="manufacturer">
                                                            <a href="product-details.html">{{ prod.brand }}</a>
                                                        </h5>
                                                    </div>
                                                    <h4><a class="product_name" href="product-detail.html">{{ prod.title }}</a></h4>
                                                    <div class="price-box">
                                                        {% if prod.is_discount %}
                                                                        <span style="color:#14EF31;" class="price">${{ prod.get_price }} - </span>
                                                                        <strike style="color:red;">{{ prod.price }}</strike>
                                                                    {% else %}
                                                                        <span class="price" style="color: #B714EF">{% trans 'No discount' %} - ${{ prod.price }}</span>
                                                                    {% endif %}
                                                    </div>
                                                </div>
                                                <div class="add-actions">
                                                    <ul class="add-actions-link">
                                                        <li class="add-cart active"><a href="{% url 'products:add_or_remove' pk=products.id %}?next={{request.get_full_path|urlencode}}">{% trans 'Add to cart' %}</a></li>
                                                        <li><a href="{% url 'products:add_or_remov' pk=products.id %}?next={{request.get_full_path|urlencode}}" title="quick view" class="quick-view-btn" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-eye"></i></a></li>
                                                        <li><a class="links-details" href="{% url 'products:add_or_remov' pk=products.id %}?next={{request.get_full_path|urlencode}}"><i class="fa fa-heart-o"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- single-product-wrap end -->
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Li's Section Area End Here -->
                    </div>
                </div>
            </section>
            <!-- Li's Laptop Product Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}

            <!-- Footer Area End Here -->
            <!-- Begin Quick View | Modal Area -->

        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
       {% include 'layouts/script.html' %}

    </body>

<!-- single-product31:32-->
</html>