blogs/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from blogs.views import BlogListView,BlogDetailView, BlogCommentView
app_name = 'blogs'





urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('comment/<int:pk>/', BlogCommentView.as_view(), name='comment'),

]

conf/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
            path('admin/', admin.site.urls),
            path('', include('pages.urls', namespace="pages")),
            path('blogs/', include('blogs.urls', namespace="blogs")),
            path('products/', include('products.urls', namespace="products")),
            path('users/', include('users.urls', namespace="users")),
            path('orders/', include('orders.urls', namespace="orders"))

)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from pages.views import HomePageView, ContactTemplateView, ThankYouView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
    path('contact/thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

]

users/urls.py
from django.urls import path
from users.views import LoginView, RegisterView, verify_email, logout_view, About, AccountView, CartView, WishlistView, \
    Faq

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/email',verify_email, name='code'),
    path('logout/', logout_view ,name='logout'),
    path('about/', About.as_view(), name='about'),
    path('accounts/', AccountView.as_view(), name='accounts'),
    path('cart/', CartView.as_view(), name='cart'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('faq/', Faq.as_view(), name='faq'),

]

blogs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from users.models import TeamModel
from django.contrib.auth.models import User


class BlogCategoryModel(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name=_('name'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class BlogTagModel(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name=_('name'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class BlogModel(models.Model):
    objects = None
    title = models.CharField(max_length=100, db_index=True, verbose_name=_('title'))
    image = models.ImageField(upload_to='blog-images', verbose_name=_('image'))
    short_info = models.TextField(null=True, verbose_name=_('short_info'))
    content = models.TextField(verbose_name=_('content'))

    category = models.ManyToManyField(BlogCategoryModel, related_name='blogs',verbose_name=_('category'))
    tags = models.ManyToManyField(BlogTagModel, related_name='tags', verbose_name=_('tags'))
    author = models.ForeignKey(TeamModel, on_delete=models.CASCADE, related_name='blogs', verbose_name=_('author'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Blog')
        verbose_name_plural = _('Blogs')


class BlogCommentModel(models.Model):
    objects = None
    blogs = models.ForeignKey(BlogModel, on_delete=models.CASCADE, related_name='comments', verbose_name=_('blogs'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name=_('user'))
    message = models.TextField(verbose_name=_('message'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

blogs/forms.py
from django import forms

from blogs.models import BlogCommentModel


class BlogsCommentModelForm(forms.ModelForm):
    class Meta:
        model = BlogCommentModel
        fields = ['message']

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView, CreateView

from blogs.forms import BlogsCommentModelForm
from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel, BlogCommentModel
from users.models import TeamModel


class BlogListView(ListView):
    template_name = 'blogs/blog-list.html'
    context_object_name = 'blogs'
    paginate_by = 3

    def get_queryset(self):
        qs = BlogModel.objects.all().order_by('-pk')
        cat = self.request.GET.get('cat')
        tag = self.request.GET.get('tag')
        q = self.request.GET.get('q')

        if cat:
            qs = qs.filter(category__in=cat)
        if tag:
            qs = qs.filter(tags__in=tag)
        if q:
            qs = qs.filter(title__icontains=q)

        return qs



    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = BlogCategoryModel.objects.all()
        context['tags'] = BlogTagModel.objects.all()
        context['famous_blogs'] = BlogModel.objects.all().order_by('-created_at')[:3]
        context["related_blogs"] = BlogModel.objects.all().order_by('-created_at')

        return context


class BlogDetailView(DetailView):
    template_name = 'blogs/blog-detail.html'
    context_object_name = 'blogs'
    model = BlogModel

    def get_object(self, *args, **kwargs):
        return BlogModel.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):
        blogs = BlogModel.objects.get(id=self.kwargs['pk'])
        content = super().get_context_data(**kwargs)
        context = {
            "author": TeamModel.objects.all(),
            "blog": BlogModel.objects.get(pk=self.kwargs['pk']),
            "category": BlogCategoryModel.objects.all(),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('-created_at')[:3],
            "related_blogs": BlogModel.objects.filter(category__in=self.object.category.all())[:3],
            'comments': BlogCommentModel.objects.filter(blogs=blogs),

        }
        return context

class BlogCommentView(LoginRequiredMixin, CreateView):
    template_name = 'blogs/blogs-detail.html'
    form_class = BlogsCommentModelForm
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        blog_id = self.kwargs['pk']
        blog = BlogModel.objects.get(pk=blog_id)
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.blogs = blog  # comment.product dan comment.blogs ga o'zgartirish
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.GET.get('next', reverse_lazy('blogs:list'))

    def form_invalid(self, form):
        return self.get_success_url()

templates/blogs/blog-detail.html
{% load static %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">
    
<!-- blog-details-left-sidebar31:56-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Blog Details' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- Begin Li's Main Blog Page Area -->
            <div class="li-main-blog-page li-main-blog-details-page pt-60 pb-60 pb-sm-45 pb-xs-45">
                <div class="container">
                    <div class="row">
                        <!-- Begin Li's Blog Sidebar Area -->
                        <div class="col-lg-3 order-lg-1 order-2">
                            <div class="li-blog-sidebar-wrapper">
                                <div class="li-blog-sidebar pt-25">
                                    <h4 class="li-blog-sidebar-title">{% trans 'Categories' %}</h4>
                                    {% for cat in category %}
                                    <ul class="li-blog-archive">
                                        <li><a href="../../?cat={{ cat.id }}" title="Show products matching tag Hot Trend">{{ cat.name }}</a></li>
                                    </ul>
                                    {% endfor %}
                                </div>
                                 <h4 class="li-blog-sidebar-title">{% trans 'Recent Post' %}</h4>
                                    {% for blogs in famous_blogs %}
                                    <div class="li-recent-post pb-30">
                                        <div class="li-recent-post-thumb">
                                            <a href="{% url 'blogs:detail' pk=blogs.id%}">
                                                <img class="img-full" src="{{ blogs.image.url }}" alt="Li's Product Image">
                                            </a>
                                        </div>
                                        <div class="li-recent-post-des">
                                            <span><a href="{% url 'blogs:detail' pk=blogs.id%}">{{ blogs.title }} |</a></span>
                                            <span class="li-post-date">{{ blogs.created_at|date}}</span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                <div class="li-blog-sidebar">
                                    <h4 class="li-blog-sidebar-title">{% trans 'Tags' %}</h4>
                                    {% for tag in tags %}
                                    <ul class="li-blog-tags">
                                        <li><a href="../../?tag={{ tag.id }}" title="Show products matching tag Hot Trend">{{ tag.name }}</a></li>
                                    </ul>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Li's Blog Sidebar Area End Here -->
                        <!-- Begin Li's Main Content Area -->
                        <div class="col-lg-9 order-lg-2 order-1">
                            <div class="row li-main-content">
                                <div class="col-lg-12">
                                    <div class="li-blog-single-item pb-30">
                                        <div class="li-blog-banner">
                                            <a href="blog-detail.html"><img class="img-full" src="{{ blog.image.url}}" alt=""></a>
                                        </div>
                                        <div class="li-blog-content">
                                            <div class="li-blog-details">
                                                <h3 class="li-blog-heading pt-25"><a href="#">{{ blog.title }}</a></h3>
                                                <div class="li-blog-meta">
                                                    <a class="author" href="#"><i class="fa fa-user"></i>{{ blog.author }}</a>
                                                    <a class="post-time" href="#"><i class="fa fa-calendar"></i>{{ blog.created_at|date}}</a>
                                                </div>
                                                <p>{{blog.content}}</p>
                                                <!-- Begin Blog Blockquote Area -->
                                                <div class="li-blog-blockquote">
                                                    <blockquote>
                                                        <p>{{ blog.short_info }}</p>
                                                    </blockquote>
                                                </div>
                                                <!-- Blog Blockquote Area End Here -->
                                                <div class="li-tag-line">
                                                    <h4>{% trans 'tag' %}:</h4>
                                                    {% for tag in tags %}
                                                    <a href="#">{{ tag.name }}</a>,
                                                    {% endfor %}
                                                </div>
                                                <div class="li-blog-sharing text-center pt-30">
                                                    <h4>{% trans 'share this post' %}:</h4>
                                                    <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                                                    <a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
                                                    <a href="https://www.pinterest.com/"><i class="fa fa-pinterest"></i></a>
                                                    <a href="https://www.google.com/"><i class="fa fa-google-plus"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Begin Li's Blog Comment Section -->
                                    <div class="li-comment-section">
                                        <h3>{{ comments.count }} {% trans 'comment' %}</h3>
                                        <ul>
                                            <li>
                                                {% for comment in comments %}
                                                <div class="author-avatar pt-15">
                                                    <img src="{%static 'images/product-details/admin.png '%}" alt="User">
                                                </div>
                                                <div class="comment-body pl-15">
                                                    <h5 class="comment-author pt-15">{{ comment.user.username }}</h5>
                                                    <div class="comment-post-date">
                                                        {{ comment.created_at|date }}
                                                    </div>
                                                    <p>
                                                        {{comment.message}}
                                                    </p>
                                                </div>
                                                {% endfor %}
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- Li's Blog Comment Section End Here -->
                                    <!-- Begin Blog comment Box Area -->
                                    <div class="li-blog-comment-wrapper">
                                        <form method="post" action="{% url 'blogs:comment' pk=blog.id %}?next={{ request.get_full_path|urlencode }}">
                                            {% csrf_token %}
                                            <div class="comment-post-box">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <label>{% trans 'comment' %}</label>
                                                        <textarea name="message" placeholder="{% trans 'message' %}"></textarea>
                                                    </div>
                                                    <div class="col-lg-12">
                                                        <div class="coment-btn pt-30 pb-sm-30 pb-xs-30 f-left">
                                                            <input class="li-btn-2" type="submit" name="submit" value="{% trans 'Send message' %}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- Blog comment Box Area End Here -->
                                </div>
                            </div>
                        </div>
                        <!-- Li's Main Content Area End Here -->
                    </div>
                </div>
            </div>
            <!-- Li's Main Blog Page Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}
            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
       {% include 'layouts/script.html' %}
    </body>

<!-- blog-details-left-sidebar32:00-->
</html>

templates/blogs/blog-list.html
{% load static %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">

<!-- blog-list-left-sidebar31:55-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Blog list' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- Begin Li's Main Blog Page Area -->
            <div class="li-main-blog-page pt-60 pb-55">
                <div class="container">
                    <div class="row">
                        <!-- Begin Li's Blog Sidebar Area -->
                        <div class="col-lg-3 order-lg-1 order-2">
                            <div class="li-blog-sidebar-wrapper">
                                <div class="li-blog-sidebar">
                                </div>
                                <div class="li-blog-sidebar pt-25">
                                    <h4 class="li-blog-sidebar-title">{% trans 'Categories' %}</h4>
                                    {% for cat in categories %}
                                    <ul class="li-blog-archive">
                                        <li><a style="cursor: pointer" onclick="addUrlParameter('cat','{{ cat.pk }}')"
                                           title="Show products matching tag Hot Trend">{{ cat.name }}</a></li>
                                    </ul>
                                    {% endfor %}
                                </div>
                                <div class="li-blog-sidebar">
                                    <h4 class="li-blog-sidebar-title">{% trans 'Recent Post' %}</h4>
                                    {% for blogs in famous_blogs %}
                                    <div class="li-recent-post pb-30">
                                        <div class="li-recent-post-thumb">
                                            <a href="{% url 'blogs:detail' pk=blogs.id%}">
                                                <img class="img-full" src="{{ blogs.image.url }}" alt="Li's Product Image">
                                            </a>
                                        </div>
                                        <div class="li-recent-post-des">
                                            <span><a href="{% url 'blogs:detail' pk=blogs.id%}">{{ blogs.title }}</a></span>
                                            <span class="li-post-date">{{ blogs.created_at|date}}</span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <div class="li-blog-sidebar">
                                    <h4 class="li-blog-sidebar-title">{% trans 'Tags' %}</h4>
                                    {% for tag in tags %}
                                    <ul class="li-blog-tags">
                                        <li><a style="cursor: pointer" onclick="addUrlParameter('tag','{{ tag.pk }}')"
                                           title="Show products matching tag Hot Trend">{{ tag.name }}</a></li>
                                    </ul>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Li's Blog Sidebar Area End Here -->
                        <!-- Begin Li's Main Content Area -->
                        <div class="col-lg-9 order-lg-2 order-1">
                            <div class="row li-main-content">
                                <div class="col-lg-12">
                                    <div class="li-blog-single-item mb-30">
                                        <div class="row">
                                            {% for blog in blogs %}
                                            <div class="col-lg-6">
                                                <div class="li-blog-banner">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}"><img class="img-full" src="{{ blog.image.url }}" alt=""></a>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="li-blog-content">
                                                    <div class="li-blog-details">
                                                        <h3 class="li-blog-heading pt-xs-25 pt-sm-25"><a href="{% url 'blogs:detail' pk=blog.id%}">{{ blog.title }}</a></h3>
                                                        <div class="li-blog-meta">
                                                            <a class="author" href="{% url 'users:about'%}"><i class="fa fa-user"></i>{{ blog.author }}</a>
                                                            <a class="post-time" href="{% url 'blogs:detail' pk=blog.id%}"><i class="fa fa-calendar"></i>{{ blog.created_at|date}}</a>
                                                        </div>
                                                        <p>{{ blog.content }}</p>
                                                        <a class="read-more" href="{% url 'blogs:detail' pk=blog.id%}">{% trans 'Read More...' %}</a>
                                                    </div>
                                                </div>
                                            </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>

                                <!-- Begin Li's Pagination Area -->
                                <div class="col-lg-12">
                                    <div class="li-paginatoin-area text-center pt-25">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <ul class="li-pagination-box">
                                                    {% if page_obj.has_previous %}
                                                    <li><a class="Previous" href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a></li>
                                                     {% endif %}
                                                    {% for page in page_obj.paginator.page_range %}
                                                    <li {% if page == page_obj.number %} class="active">{% endif %}
                                                        <a href="?page={{ page }}">
                                                        </a>
                                                    </li>
                                                    {% endfor %}
                                                    {% if page_obj.has_next %}
                                                    <li><a class="Next" href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a></li>
                                                    {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Li's Pagination End Here Area -->
                            </div>
                        </div>
                        <!-- Li's Main Content Area End Here -->
                    </div>
                </div>
            </div>
            <!-- Li's Main Blog Page Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}
            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
       {% include 'layouts/script.html' %}

    </body>

<!-- blog-list-left-sidebar31:56-->
</html>

<script>
    function addUrlParameter(name, value){
        let searchParams = new URLSearchParams(window.location.search)
        if (searchParams.has(name) && searchParams.get(name) == value) {
            searchParams.delete(name)
        } else {
            searchParams.set(name, value)
        }
        window.location.search = searchParams.toString()
    }
</script>